version: '2'
services:
  mautic:
    image: mautic/mautic
    restart: always
    links:
    - mauticdb:mysql
    ports:
    - "5000:80"

  mauticdb:
    image: mysql:5.6
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD
