version: '2'
services:
  bot:
   image: janruehling/poloniexlendingbot
   restart: always
   working_dir: /usr/src/app
   ports:
      - "0.0.0.0:8000:8000"
   volumes:
      - "/usr/src/app"
   # command: bash -c "python lendingbot.py"
   environment:
      - API_KEY='add_your_own_key'
      - API_SECRET='get_your_secret_from_poloniex'
      - USE_TELEGRAM=False
      - TELEGRAM_BOT_ID='get_telegram_bot_id'
      - TELEGRAM_CHAT_IDS='comma_seperated_chat_ids'
