version: '2'
services:
  bot:
   image: janruehling/poloniexlendingbot
   restart: always
   ports:
   - "8000:8000"
   command: bash -c "python lendingbot.py"
   environment:
      - USE_TELEGRAM=False
