version: '2'
services:
  bot:
   image: janruehling/poloniexlendingbot
   restart: always
   working_dir: /usr/src/app
   ports:
   - 8000:8000
   # command: bash -c "python lendingbot.py"
   environment:
   - API_KEY
   - API_SECRET
   - USE_TELEGRAM=False
   - TELEGRAM_ID
   - TELEGRAM_CHATS
