version: '2'
catalog:
  name: Poloniex Lendingbot # Name of the versioned template of the Catalog Entry
  version: 1.0.0 # Version of the versioned template of the Catalog Entry
  description: A bot that lends cryptocurrency on Poloniex.com # Description of the versioned template of the Catalog Entry
  minimum_rancher_version: v1.6.2 # The minimum version of Rancher that supports the template, v1.0.1 and 1.0.1 are acceptable inputs
  maximum_rancher_version: v1.6.2 # The maximum version of Rancher that supports the template, v1.0.1 and 1.0.1 are acceptable inputs
  upgrade_from: 1.0.0 # The previous versions that this template can be upgraded from
  questions: #Used to request user input for configuration options
    - variable: API_KEY
      label: Poloniex API key
      description: |
        Enter your API key from Poloniex
      required: true
      type: string
    - variable: API_SECRET
      label: Poloniex API secret
      description: |
        Enter your API secret from Poloniex
      required: true
      type: string
    - variable: USE_TELEGRAM
      label: Do you want to use Telegram?
      description: |
        Choose if you want to use Telegram or not
      type: enum
      options:
      - 'true'
      - 'false'
      default: 'false'
    - variable: TELEGRAM_ID
      label: Telegram Bot ID
      description: |
        Enter the bot ID that you got from Telegram. This is required if you use Telegram
      type: string
    - variable: TELEGRAM_CHATS
      label: Telegram chat ids
      description: |
        Enter the chat ids as a comma-separated list. This is required if you use Telegram
      type: string
