name: Poloniex Lendingbot
description: |
  A bot that lends crypto on Poloniex.com
version: 1.0.0
category: Bots
maintainer: janruehling@gmail.com # The maintainer of the catalog entry
license: MIT
projectURL: https://github.com/janruehling/poloniexlendingbot
