name: Poloniex Lendingbot # Name of the Catalog Entry
description: |
  # Description of the Catalog Entry
  A bot that lends crypto on Poloniex.com
version: 1.0.0 # Version of the Catalog to be used
category: Bots # Category to be used for searching catalog entries
maintainer: janruehling@gmail.com # The maintainer of the catalog entry
license: MIT # The license
projectURL: https://github.com/janruehling/poloniexlendingbot # A URL related to the catalog entry
